# Generated by Django 3.2.3 on 2021-05-29 15:59

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('delivery_status', models.CharField(default='processing', max_length=20)),
                ('order_quantity', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(default=None, upload_to='static/product_images')),
                ('product_ratings', models.FloatField()),
                ('product_stock', models.IntegerField()),
                ('product_category', models.CharField(default=None, max_length=200)),
                ('isvalid_for_offer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('mobile', models.BigIntegerField()),
                ('auth_token', models.CharField(max_length=500)),
                ('user_image', models.ImageField(default=None, upload_to='static/user_images')),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=300)),
                ('landmark', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='api.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_entry_date', models.DateTimeField(auto_now=True)),
                ('product_description', models.CharField(max_length=500)),
                ('offer_end_date', models.DateTimeField()),
                ('product_brand', models.CharField(default=None, max_length=200)),
                ('manufacturer', models.CharField(default=None, max_length=200)),
                ('product_details', models.TextField(default=None, help_text='example: key=value and seprate by comma(,) ', validators=[api.models.json_validation])),
                ('product_id', models.ForeignKey(db_column='product_name', on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200)),
                ('user_id', models.BigIntegerField()),
                ('product_id', models.BigIntegerField()),
                ('payment_id', models.CharField(default='', max_length=200)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(max_length=40)),
                ('amount_paid', models.BooleanField(default=False)),
                ('payment_mode', models.IntegerField()),
                ('order_receipt_id', models.CharField(max_length=100)),
                ('order_quantity', models.IntegerField(default=1)),
                ('order_id', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='api.userlogin')),
            ],
        ),
    ]
