# Generated by Django 3.2.3 on 2021-05-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderdetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='order_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='user_id',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='api.userlogin'),
        ),
    ]
