# Generated by Django 3.2.3 on 2021-06-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_servicebooking_service_assign_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service_assign_to',
            field=models.ForeignKey(db_column='employee_name', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
            preserve_default=False,
        ),
    ]
