# Generated by Django 3.2.3 on 2021-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210529_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='sub_category',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
