# Generated by Django 3.2.3 on 2021-06-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_servicebooking_service_closed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employeeId',
            new_name='employee_id',
        ),
    ]
