# Generated by Django 3.2.3 on 2021-06-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_employeeid_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_join',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_resign',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
