# Generated by Django 3.2.3 on 2021-05-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userlogin_is_address_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWish',
        ),
    ]
